browser:
  navigate: { timeout: 20, retries: 1 }
  search: { timeout: 15, retries: 1 }
  click: { timeout: 8, retries: 1 }
  type: { timeout: 5, retries: 1 }
  upload: { timeout: 60, retries: 0 }
  extract: { timeout: 10, retries: 1 }
files:
  search: { timeout: 10, retries: 1 }
  read_text: { timeout: 8, retries: 1 }
  open: { timeout: 8, retries: 0 }
